name: my_template
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  #universal
  flutter:
    sdk: flutter
  firebase_auth: any
  firebase_auth_web: ^5.12.4
  http: any
  cloud_firestore: any
  dartz: any
  easy_localization: any
  firebase_analytics: any
  firebase_core: any
  firebase_crashlytics: any
  firebase_cloud_firestore: ^5.0.1
  firebase_storage: any
  flutter_bloc: any
  freezed: any
  get_it: any
  go_router: any
  injectable: any
  logger: any
  flutter_flavorizr: any
  json_annotation: ^4.9.0
  url_launcher: any

  #web
  flutter_web_plugins:
    sdk: flutter

  #specific
  langchain: any
  langchain_community: any
  langchain_openai: any

  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: any
  flutter_lints: any 
  flutter_test:
    sdk: flutter
  injectable_generator: any
  json_serializable: any
  path: any



flutter:
  generate: true
  uses-material-design: true

  
  assets:
    - assets/translations/
    - assets/
    - assets/images/

