// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy7DUfD-k-KZjkRbFBH6M-8ypLTq14p9Q',
    appId: '1:260962086306:web:eb41ee037fec1a39ca96fb',
    messagingSenderId: '260962086306',
    projectId: 'my-template-dev',
    authDomain: 'my-template-dev.firebaseapp.com',
    storageBucket: 'my-template-dev.appspot.com',
    measurementId: 'G-L88XENFTNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDldKplkGbl7xLXl_1pR4v58mxmFGXdRI4',
    appId: '1:260962086306:android:b04e4d6fe70e118bca96fb',
    messagingSenderId: '260962086306',
    projectId: 'my-template-dev',
    storageBucket: 'my-template-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB6proTo6B814WsofYKPuOryiVtvctR3o',
    appId: '1:260962086306:ios:a09843cb888563f0ca96fb',
    messagingSenderId: '260962086306',
    projectId: 'my-template-dev',
    storageBucket: 'my-template-dev.appspot.com',
    iosClientId: '260962086306-lvjr46bb05gpo97l772rng5l9esni7b7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterTemplate',
  );
}
